[package]
name = "lexer_gen"
version = "0.1.5"
authors = ["Pierre-Andre Gagnon <pagagnon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
